apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "okdp-ui.fullname" . }}
  labels:
    {{- include "okdp-ui.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.ingress.clusterIssuer }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  tls:
    - hosts:
        - {{ .Values.ingress.host | quote }}
      secretName: {{ .Values.ingress.tlsSecretName }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "okdp-ui.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
